### ISSUE TITLE
after i format document,the user stats broken...

### ISSUE THREAD

**Issue by zeroninefourfour** [WybeNetwork/VistaPanel-Demo#1] opened 2022-08-20 02:08 UTC
<img width="1005" alt="截圖 2022-08-20 上午10 07 46" src="https://user-images.githubusercontent.com/69704016/185725168-34cdd726-75ae-4e85-a570-209f3b6e8cac.png">
is possible to format it without make it broken.?

**Comment by 4yx** [comment] 2022-08-25 22:54
I made some changes, but was unable to replicate the issue. What do you mean by "format" it?
Additionally, I visited your repo's demo and everything seemed to be working fine.

Could you post the changes you made that break it?

**Comment by zeroninefourfour** [comment] 2022-08-26 01:01
<img width="611" alt="截圖 2022-08-26 上午9 00 50" src="https://user-images.githubusercontent.com/69704016/186794425-fcafd95c-3984-4e86-9d2a-ee146e777737.png">
format the code,user stats broken.

**Comment by 4yx** [comment] 2022-08-28 20:37
I was able to replicate this; for some reason, it appears that when using VSCode/ium's Format Document, an extra </div> closing tag is added (well, either that or the closing tag is moved), closing the div.row inside the main content sooner than expected.
I have no idea why that happens though, and I'm not sure if there's something that can be done to fix it. I'm open to suggestions.

**Comment by aa22dev** [comment] 2022-09-08 16:46
That is not the bug with this repo, that issue is actually caused by VSCode formatter. After replicating your issue, I found out that In the process of formatting the document VSCode is moving `<div id="stats"` outside from `<div class="row"` in which `<div id="main"` exists, which was causing the main element to cover the whole available width. You can fix it by removing extra closing div tag, reformatting the document and moving `<div id="stats"` inside the `<div class="row"` element.
This should fix the issue you are facing.

As a reference, you can check this sub-branch file formatted through VSCode: https://github.com/WybeNetwork/VistaPanel-Demo/blob/mahofficial-patch-1/formatted.index.html (It works fine)

**Closed as completed by aa22dev** 2022-09-08 16:46 UTC
Labels: question

**Comment by zeroninefourfour** [comment] 2022-09-18 10:47
oh thanks
